language: android
jdk: oraclejdk8
addons:
  apt:
    packages:
      - xsltproc
      - xmlstarlet
android:
  components:
    - tools # to get the new `repository-11.xml`
    - platform-tools
    - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - build-tools-25.0.1
    - android-22
    - android-25
# Without these the build fails
    - extra-google-m2repository
    - extra-android-m2repository
#    - sys-img-armeabi-v7a-android-25
#    - sys-img-armeabi-v7a-google_apis-22
# fails with: emulator: ERROR: x86 emulation currently requires hardware acceleration! CPU acceleration status: KVM requires a CPU that supports vmx or svm
#    - sys-img-x86-google_apis-22

# To automatically accept various licenses when prompted, so that we don't get stuck
licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

# Emulator Management: Create, Start and Wait
before_script:
#  - android list targets
#  - echo no | android create avd --force -n test -t android-22 --abi armeabi-v7a --tag google_apis
#  - emulator -avd test -no-audio -no-window &
#  - android-wait-for-emulator
#  - adb shell input keyevent 82 &

script:
    - ./scripts/start-ci-cd.bash
#    - if ! ./scripts/local-wrapper.bash; then echo "Build failed"; travis_terminate 1; fi
#    - cd Examples/restcomm-olympus && ./gradlew build 
